version: '3.3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myway
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5435:5435
    command: -p 5435
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5435/myway
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
volumes:
  data: