# Generated by Django 3.1.2 on 2021-01-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trippoint',
            name='point',
        ),
    ]
