# Generated by Django 3.1.2 on 2021-01-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210130_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showobject',
            name='events',
            field=models.ManyToManyField(blank=True, to='core.Event'),
        ),
        migrations.AlterField(
            model_name='showobject',
            name='persons',
            field=models.ManyToManyField(blank=True, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='showobject',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
