# Generated by Django 3.1.2 on 2021-01-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_trippoint_point'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trippoint',
            constraint=models.UniqueConstraint(fields=('trip', 'point'), name='trip_point'),
        ),
    ]
