# Generated by Django 3.1.2 on 2021-01-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210129_1417'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trippoint',
            name='trip_point',
        ),
    ]
