# Generated by Django 3.1.2 on 2021-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210130_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='events',
            field=models.ManyToManyField(blank=True, to='core.Event'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
