# Generated by Django 3.1.2 on 2021-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eventsite_objectsite_personsite_site_tagsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='showobject',
            name='sites',
            field=models.ManyToManyField(blank=True, to='core.Site'),
        ),
    ]
