# Generated by Django 3.1.2 on 2021-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_showobject_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='showobject',
            name='last_version_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='showobject',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='showobject',
            name='style',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
